
CREATE DATABASE PHOTO_FORUM
	USE PHOTO_FORUM
BEGIN TRANSACTION
	

	--PHOTO WEB
	CREATE TABLE PHOTO_USER(
		USERNAME VARCHAR(250) PRIMARY KEY,
		PASSWORD VARCHAR(250) NOT NULL,
		EMAIL VARCHAR(250) NOT NULL,
		STATUS BIT NOT NULL,
		ROLE VARCHAR(20) NOT NULL,
		IMG VARCHAR(250) NOT NULL
	)
	CREATE TABLE IMG(
		IMG_ID INT IDENTITY(1,1) PRIMARY KEY,
		USERNAME VARCHAR(250) NOT NULL,
		UPLOAD_DATE DATETIME NOT NULL,
		IMG_NAME VARCHAR(250) NOT NULL,
		STATUS VARCHAR(20) NOT NULL
	)
	CREATE TABLE TAG(
		TAG_NAME VARCHAR(250) PRIMARY KEY
	)
	CREATE TABLE TAG_IMG(
		IMG_ID INT NOT NULL,
		TAG_NAME VARCHAR(250) NOT NULL
	)
	ALTER TABLE TAG_IMG ADD PRIMARY KEY (IMG_ID, TAG_NAME)
	--LINK

	--IMG_TAG
	ALTER TABLE TAG_IMG ADD CONSTRAINT FK_TAG_TAG FOREIGN KEY (TAG_NAME) REFERENCES TAG(TAG_NAME)
	ALTER TABLE TAG_IMG ADD CONSTRAINT FK_TAG_IMG FOREIGN KEY (IMG_ID) REFERENCES IMG(IMG_ID)
	--IMG
	ALTER TABLE IMG ADD CONSTRAINT FK_IMG_USER FOREIGN KEY (USERNAME) REFERENCES PHOTO_USER(USERNAME)
	

	--FORUM WEB

	CREATE TABLE FORUM_USER(
		USERNAME VARCHAR(250) PRIMARY KEY,
		PASSWORD VARCHAR(250) NOT NULL,
		EMAIL VARCHAR(250) NOT NULL,
	)
	CREATE TABLE LINKED_USER(
		USERNAME VARCHAR(250) PRIMARY KEY NOT NULL,
		LINKED_USERNAME VARCHAR(250) NOT NULL
	)
	CREATE TABLE POST(
		ID INT IDENTITY(1,1) PRIMARY KEY,
		NAME VARCHAR(250) NOT NULL,
		USERNAME VARCHAR(250) NOT NULL,
		POST_TIME DATETIME NOT NULL,
		CAPTION TEXT NOT NULL,
		LINKED_LINK VARCHAR(250) NOT NULL
	)

	--LINK

	ALTER TABLE LINKED_USER ADD CONSTRAINT FK_LINKED_USER FOREIGN KEY (USERNAME) REFERENCES FORUM_USER(USERNAME)
	ALTER TABLE POST ADD CONSTRAINT FK_POST_USER FOREIGN KEY (USERNAME) REFERENCES FORUM_USER(USERNAME)
	GO
	CREATE PROCEDURE SELECT_NEWEST_IMG @USERNAME nvarchar(250)
	AS
	BEGIN
		SELECT TOP 1 * FROM IMG WHERE USERNAME = @USERNAME ORDER BY IMG_ID DESC
	END
	EXEC SELECT_NEWEST_IMG @USERNAME = "USER1"
COMMIT;
