//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forum.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PHOTO_FORUMEntities : DbContext
    {
        public PHOTO_FORUMEntities()
            : base("name=PHOTO_FORUMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FORUM_USER> FORUM_USER { get; set; }
        public virtual DbSet<LINKED_USER> LINKED_USER { get; set; }
        public virtual DbSet<POST> POSTs { get; set; }
    }
}
