//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POST
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string USERNAME { get; set; }
        public System.DateTime POST_TIME { get; set; }
        public string CAPTION { get; set; }
        public string LINKED_LINK { get; set; }
    
        public virtual FORUM_USER FORUM_USER { get; set; }
    }
}
