//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoForum.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMG()
        {
            this.TAGs = new HashSet<TAG>();
        }
    
        public int IMG_ID { get; set; }
        public string USERNAME { get; set; }
        public System.DateTime UPLOAD_DATE { get; set; }
        public string IMG_NAME { get; set; }
        public string STATUS { get; set; }
    
        public virtual PHOTO_USER PHOTO_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAG> TAGs { get; set; }
    }
}
